repos:
  - repo: https://github.com/fastai/nbdev
    rev: 3.0.12
    hooks:
      - id: nbdev-clean
      - id: nbdev-export

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)(
            ^README\.md$
            | ^docs/
            | ^nbdev_fhemb/_modidx\.py$
            | ^nbdev_fhemb/.*\.py$
          )

      - id: end-of-file-fixer
        exclude: |
          (?x)(
            ^README\.md$
            | ^docs/
            | ^nbdev_fhemb/_modidx\.py$
            | ^nbdev_fhemb/.*\.py$
          )
