# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_fhemb',
                'doc_host': 'https://rdned.github.io',
                'git_url': 'https://github.com/rdned/nbdev_fhemb',
                'lib_path': 'nbdev_fhemb'},
  'syms': {'nbdev_fhemb.core': {'nbdev_fhemb.core.foo': ('core.html#foo', 'nbdev_fhemb/core.py')}, 'nbdev_fhemb.tfreq': {}}}
