# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/dtw_classification.ipynb.

# %% auto #0
__all__ = ['dg0']

# %% ../nbs/dtw_classification.ipynb #803a181d
dg0 = Piece(title='Don Giovanni', time_interval=(14200,15200), subjs=[(65,68)])
