# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/embeddings.ipynb.

# %% auto #0
__all__ = ['dg0']

# %% ../nbs/embeddings.ipynb #559fc09b
dg0 = Piece(title='Don Giovanni', time_interval=(14200,15200), subjs=[(65,68)])
