# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/lagged_ccorr.ipynb.

# %% auto #0
__all__ = ['dg0', 'pca2']

# %% ../nbs/lagged_ccorr.ipynb #5f2960b3
dg0 = Piece(title='Don Giovanni', time_interval=(14200,15200), subjs=[(65,68)])

# %% ../nbs/lagged_ccorr.ipynb #862c8b78
pca2 = pca_factory(
    name='standard_kpca_5_sigmoid_0.07', 
    scaler='Standard', 
    pca='Kernel',
    scaler_kwargs=dict(with_std=True), 
    pca_kwargs=dict(n_components=5, kernel='sigmoid', gamma=0.07, fit_inverse_transform=True)
)
