"""Analysis of time series embeddings"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/tfreq.ipynb.

# %% auto 0
__all__ = ['dg0', 'pca1', 'pca2', 'pca3', 'pca4', 'pca5', 'pca6', 'pca7', 'pca8', 'pca9', 'pca10', 'pca11', 'pca12', 'pca13']

# %% ../nbs/tfreq.ipynb 7
dg0 = Piece(title='Don Giovanni', time_interval=(14200,16200), subjs=[(60,70)])

# %% ../nbs/tfreq.ipynb 9
pca1 = pca_factory(
    name='standard_kpca_5_sigmoid_0.1', 
    scaler='Standard', 
    pca='Kernel', 
    scaler_kwargs=dict(with_std=False), 
    pca_kwargs=dict(n_components=5, kernel='sigmoid', gamma=0.1, fit_inverse_transform=True)
)

# %% ../nbs/tfreq.ipynb 10
pca2 = pca_factory(
    name='standard_kpca_5_sigmoid_0.07', 
    scaler='Standard', 
    pca='Kernel',
    scaler_kwargs=dict(with_std=True), 
    pca_kwargs=dict(n_components=5, kernel='sigmoid', gamma=0.07, fit_inverse_transform=True)
)

# %% ../nbs/tfreq.ipynb 11
pca3 = pca_factory(
    name='center_kpca_5_rbf_1', 
    scaler='Standard', 
    pca='Kernel',
    scaler_kwargs=dict(with_std=False), 
    pca_kwargs=dict(n_components=5, kernel='rbf', gamma=1, fit_inverse_transform=True)
)

# %% ../nbs/tfreq.ipynb 12
pca4 = pca_factory(
    name='center_kpca_5_poly_04', 
    scaler='Standard', 
    pca='Kernel',
    scaler_kwargs=dict(with_std=False), 
    pca_kwargs=dict(n_components=5, kernel='poly', gamma=0.04, fit_inverse_transform=True)
)

# %% ../nbs/tfreq.ipynb 13
pca5 = pca_factory(
    name='center_spca_5_05', 
    scaler='Standard', 
    pca='Sparse',
    scaler_kwargs=dict(with_std=False), 
    pca_kwargs=dict(n_components=5, alpha=0.5)
)

# %% ../nbs/tfreq.ipynb 14
pca6 = pca_factory(
    name='center_kpca_5_linear_1', 
    scaler='Standard', 
    pca='Kernel',
    scaler_kwargs=dict(with_std=True), 
    pca_kwargs=dict(n_components=5, kernel= 'linear', gamma=1, fit_inverse_transform=True)
)

# %% ../nbs/tfreq.ipynb 15
pca7 = pca_factory(
    name='std_kpca_5_rbf_1', 
    scaler='Standard', 
    pca='Kernel',
    scaler_kwargs=dict(with_std=True), 
    pca_kwargs=dict(n_components=5, kernel= 'rbf', gamma=1, fit_inverse_transform=True) # gamma=0.008
)

# %% ../nbs/tfreq.ipynb 16
pca8 = pca_factory(
    name='robust_kpca_5_linear_1', 
    scaler='Robust', 
    pca='Kernel',
    scaler_kwargs=dict(), 
    pca_kwargs=dict(n_components=5, kernel= 'linear', gamma=1, fit_inverse_transform=True) # gamma=0.008
)

# %% ../nbs/tfreq.ipynb 17
pca9 = pca_factory(
    name='robust_kpca_5_rbf_1', 
    scaler='Robust', 
    pca='Kernel',
    scaler_kwargs=dict(), 
    pca_kwargs=dict(n_components=5, kernel= 'rbf', gamma=1, fit_inverse_transform=True) # gamma=0.008
)

# %% ../nbs/tfreq.ipynb 18
pca10 = pca_factory(
    name='robust_kpca_5_poly_1', 
    scaler='Robust', 
    pca='Kernel',
    scaler_kwargs=dict(), 
    pca_kwargs=dict(n_components=5, kernel= 'poly', gamma=1, fit_inverse_transform=True) # gamma=0.008
)

# %% ../nbs/tfreq.ipynb 19
pca11 = pca_factory(
    name='robust_kpca_5_sigmoid_1', 
    scaler='Robust', 
    pca='Kernel',
    scaler_kwargs=dict(), 
    pca_kwargs=dict(n_components=5, kernel= 'sigmoid', gamma=1, fit_inverse_transform=True) # gamma=0.008
)

# %% ../nbs/tfreq.ipynb 20
pca12 = pca_factory(
    name='robust_spca_5_05', 
    scaler='Robust', 
    pca='Sparse',
    scaler_kwargs=dict(), 
    pca_kwargs=dict(n_components=5, alpha=0.5)
)


# %% ../nbs/tfreq.ipynb 21
pca13 = pca_factory(
    name='center_rpca', 
    scaler='Standard', 
    pca='Robust',
    scaler_kwargs=dict(with_std=False), 
    pca_kwargs=dict()
)
